# Generated by Django 5.2 on 2025-04-07 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EcoAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('water', models.PositiveIntegerField(default=0)),
                ('electricity', models.PositiveIntegerField(default=0)),
                ('bags', models.PositiveIntegerField(default=0)),
                ('rides', models.PositiveIntegerField(default=0)),
                ('compost', models.PositiveIntegerField(default=0)),
                ('plastic', models.PositiveIntegerField(default=0)),
                ('trees', models.PositiveIntegerField(default=0)),
                ('walk', models.PositiveIntegerField(default=0)),
                ('cycle', models.PositiveIntegerField(default=0)),
                ('ac_heater', models.PositiveIntegerField(default=0)),
                ('natural_light', models.PositiveIntegerField(default=0)),
                ('food_waste', models.PositiveIntegerField(default=0)),
                ('reused', models.PositiveIntegerField(default=0)),
                ('refilled_bottle', models.PositiveIntegerField(default=0)),
                ('donated_clothes', models.PositiveIntegerField(default=0)),
                ('idle_devices', models.PositiveIntegerField(default=0)),
                ('custom_action', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
